apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Values.APPLICATION_NAME }}-deployment'
  namespace: '{{ .Values.NAMESPACE }}'
spec:
  replicas: '{{ .Values.DEPLOYMENT.NUMBER_OF_REPLICAS }}'
  selector:
    matchLabels:
      app: '{{ .Values.APPLICATION_NAME }}-pod'
  template:
    metadata:
      labels:
        app: '{{ .Values.APPLICATION_NAME }}-pod'
    spec:
      containers:
        - env:
            - name: PREVIEW_SERVER_URL
              value: https://dev-preview-server.internal.tf-b2c.com
            - name: CONTAINER_CONFIG
              valueFrom:
                secretKeyRef:
                  key: gtm-container-config
                  name: '{{ .Values.APPLICATION_NAME }}-secrets-new'
          image: '{{ .Values.DEPLOYMENT.CONTAINER.IMAGE }}:{{ .Values.DEPLOYMENT.CONTAINER.IMAGE_TAG }}'
          imagePullPolicy: Always
          name: '{{ .Values.APPLICATION_NAME }}-pod'
          ports:
            - containerPort: '{{ .Values.DEPLOYMENT.CONTAINER.PORT }}'
          resources:
            limits:
              memory: '{{ .Values.DEPLOYMENT.CONTAINER.RESOURCES.MEMORY_LIMIT }}'
            requests:
              cpu: '{{ .Values.DEPLOYMENT.CONTAINER.RESOURCES.CPU_REQUESTS }}'
      restartPolicy: Always
