apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: basic-auth-{{ .Values.APPLICATION_NAME }}
  namespace: '{{ .Values.NAMESPACE }}'
spec:
  backendType: systemManager
  data:
    - key: /{{ .Values.ENV }}-{{ .Values.INGRESS.BASIC_AUTH.SECRET.NAME }}-service
      name: auth
    - key: /{{ .Values.ENV }}-{{ .Values.INGRESS.BASIC_AUTH.SECRET.NAME }}-service
      name: auth_service_url
  region: '{{ .Values.AWS_REGION }}'
