apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: '{{ .Values.INGRESS.ANNOTATIONS }}{"nginx.ingress.kubernetes.io/auth-secret": "basic-auth-{{ .Values.APPLICATION_NAME }}", "nginx.ingress.kubernetes.io/auth-type": "basic"}'
  name: '{{ .Values.APPLICATION_NAME }}-ingress'
  namespace: '{{ .Values.NAMESPACE }}'
spec:
  ingressClassName: '{{ .Values.INGRESS.CLASS_NAME }}'
  rules:
    - host: '{{ .Values.DNS_PREFIX }}-{{ .Values.APPLICATION_NAME }}.{{ .Values.DNS_DOMAIN }}'
      http:
        paths:
          - backend:
              service:
                name: '{{ .Values.APPLICATION_NAME }}-service'
                port:
                  number: '{{ .Values.SERVICE.PORT }}'
            path: /
            pathType: Prefix
          - backend:
              service:
                name: '{{ .Values.APPLICATION_NAME }}-api-service'
                port:
                  number: '{{ .Values.SERVICE.PORT }}'
            path: /v1
            pathType: Prefix
