apiVersion: v1
kind: Service
metadata:
  labels:
    app: '{{ .Values.APPLICATION_NAME }}'
  name: '{{ .Values.APPLICATION_NAME }}-service'
  namespace: '{{ .Values.NAMESPACE }}'
spec:
  ports:
    - name: http-web
      port: '{{ .Values.SERVICE.PORT }}'
      targetPort: '{{ .Values.DEPLOYMENT.CONTAINER.PORT }}'
  selector:
    app: '{{ .Values.APPLICATION_NAME }}-pod'
