APPLICATION_NAME: '{{ .Values.APPLICATION_NAME }}'
AWS_REGION: '{{ .Values.AWS_REGION }}'
DEPLOYMENT:
  CONTAINER:
    ENV_VARIABLES:
      - NAME: PREVIEW_SERVER_URL
        VALUE: https://dev-preview-server.internal.tf-b2c.com
      - NAME: CONTAINER_CONFIG
        VALUE_FROM:
          SECRET_KEY_REF:
            KEY: gtm-container-config
            NAME: '{{ .Values.APPLICATION_NAME }}-secrets-new'
    IMAGE: '{{ .Values.DEPLOYMENT.CONTAINER.IMAGE }}'
    IMAGE_TAG: '{{ .Values.DEPLOYMENT.CONTAINER.IMAGE_TAG }}'
    PORT: '{{ .Values.DEPLOYMENT.CONTAINER.PORT }}'
    RESOURCES:
      CPU_REQUESTS: '{{ .Values.DEPLOYMENT.CONTAINER.RESOURCES.CPU_REQUESTS }}'
      MEMORY_LIMIT: '{{ .Values.DEPLOYMENT.CONTAINER.RESOURCES.MEMORY_LIMIT }}'
  NUMBER_OF_REPLICAS: '{{ .Values.DEPLOYMENT.NUMBER_OF_REPLICAS }}'
  POD_NAME: '{{ .Values.APPLICATION_NAME }}-pod'
DNS_DOMAIN: '{{ .Values.DNS_DOMAIN }}'
DNS_PREFIX: '{{ .Values.DNS_PREFIX }}-'
ENV: '{{ .Values.ENV }}'
EXTERNAL_SECRET:
  DATA:
    - KEY: /{{ .Values.ENV }}-{{ .Values.INGRESS.BASIC_AUTH.SECRET.NAME }}-service
      NAME: auth
    - KEY: /{{ .Values.ENV }}-{{ .Values.INGRESS.BASIC_AUTH.SECRET.NAME }}-service
      NAME: auth_service_url
INGRESS:
  ANNOTATIONS: '{{ .Values.INGRESS.ANNOTATIONS }}'
  BASIC_AUTH:
    ENABLED: true
    SECRET_NAME: basic-auth-{{ .Values.APPLICATION_NAME }}
  CLASS_NAME: '{{ .Values.INGRESS.CLASS_NAME }}'
  PATHS:
    - PATH: /
      PORT: '{{ .Values.SERVICE.PORT }}'
      SERVICE_NAME: '{{ .Values.APPLICATION_NAME }}-service'
    - PATH: /v1
      PORT: '{{ .Values.SERVICE.PORT }}'
      SERVICE_NAME: '{{ .Values.APPLICATION_NAME }}-api-service'
NAMESPACE: '{{ .Values.NAMESPACE }}'
SERVICE:
  PORT: '{{ .Values.SERVICE.PORT }}'
  TARGET_PORT: '{{ .Values.DEPLOYMENT.CONTAINER.PORT }}'
