resources:
  - ../../base

# Unique namespace for the dev environment
namespace: tf-flash-dev

# Merge the dev.env file with the base.env file to create the ConfigMap
configMapGenerator:
  - name: configmap
    behavior: replace
    envs:
      - _dev.env

# Replaces the placeholders in the manifests with the values from the replacements.yaml file
replacements:
  - path: replacements.yaml